# Generated by Django 3.1.5 on 2021-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210116_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Client', 'Client')], max_length=10),
        ),
    ]
