# Generated by Django 3.1.5 on 2021-01-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210118_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projecttechnology',
            name='title',
        ),
        migrations.DeleteModel(
            name='BlogCategories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
