# Generated by Django 3.1.5 on 2021-01-18 13:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210118_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='home.TaggedTechnologies', to='home.ProjectTechnology', verbose_name='Technologies'),
        ),
    ]
