# Generated by Django 3.1.5 on 2021-01-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
