# Generated by Django 3.1.5 on 2021-01-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='categories',
        ),
    ]
